title: Actors
modelClass: DigArt\Kino\Models\Actor
list: $/digart/kino/models/actor/columns.yaml
recordUrl: 'digart/kino/actors/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: last_name
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
