title: Status
modelClass: DigArt\Kino\Models\Status
list: $/digart/kino/models/status/columns.yaml
recordUrl: 'digart/kino/status/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: name
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
